#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn commitlint --edit "$1" < /dev/null

linted_tag="[linted]"

if grep -q "$linted_tag" "$1"; then
  exit 0
fi

echo "$(cat "$1") $linted_tag" > "$1"