#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn commitlint --edit $1

linted_tag="[linted]"

# Check if the commit message already contains [linted]
if grep -q "$linted_tag" "$1"; then
  exit 0
fi

# Append [linted] to the commit message
echo "$(cat "$1") $linted_tag" > "$1"